name: "Calibre-Web"
description: "Host your own web library"
version: "0.6.25.1"
slug: "calibre-web"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8083/tcp: 8083
url: https://github.com/janeczku/calibre-web
webui: http://[HOST]:[PORT:8083]
map:
  - share
  - media
